title: My first web page
theme: minima
author: Abdullah Asghar
email: abdullah.asghar@algo.com
description: > # Don't you dare to ignore until "baseurl:"
  This description is to warn you don't you dare to hack this page. I'm the owner and i'm coming for you if you dare to. ^_^

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
